-- MySQL Script generated by MySQL Workbench
-- 03/11/17 09:44:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema calories_calculator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `calories_calculator` ;

-- -----------------------------------------------------
-- Schema calories_calculator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `calories_calculator` DEFAULT CHARACTER SET utf8 ;
USE `calories_calculator` ;

-- -----------------------------------------------------
-- Table `calories_calculator`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calories_calculator`.`activity` ;

CREATE TABLE IF NOT EXISTS `calories_calculator`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `mets` DECIMAL(3,1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO appuser;
 DROP USER appuser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'appuser' IDENTIFIED BY 'student';

GRANT SELECT ON TABLE `calories_calculator`.* TO 'appuser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `calories_calculator`.`activity`
-- -----------------------------------------------------
START TRANSACTION;
USE `calories_calculator`;
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (1, 'walking', 2.5);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (2, 'volleyball', 3.0);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (3, 'calisthenics', 4.0);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (4, 'golf', 4.5);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (5, 'cycling', 4.5);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (6, 'dancing', 4.8);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (7, 'swimming', 5.0);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (8, 'tennis', 7.5);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (9, 'basketball', 8.0);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (10, 'soccer', 10.0);
INSERT INTO `calories_calculator`.`activity` (`id`, `name`, `mets`) VALUES (11, 'running', 12.0);

COMMIT;

